### PR TITLE
removed the ability to expose network as a claim

### LINKED ISSUE #18: `CompositeNetwork` XRD should not offer a claim
Very similar to https://github.com/upbound/platform-ref-aws/issues/25, this GCP configuration offers a Network claim that doesn't really make sense to expose to application developers.  We should update platform-ref-gcp to no longer expose these infrastructure complexity/details to end user app devs.

@natereid72 has removed this claim and refactored the compositions to no longer expose the Network as a claim in https://github.com/upbound/platform-ref-azure/pull/3.  That PR will provide a great example of the work that is needed here in GCP.

### PR DESCRIPTION
**Pull request by ldalorion**
Signed-off-by: Dalorion Johnson <dalorion@upbound.io>

### Description of your changes

Remove the ability to create a CompositeNetwork claim. 

Fixes #18 

I have:

- [X] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [N/A] Run `make reviewable` to ensure this PR is ready for review.
- [N/A] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

Tested in Upbound Cloud in my own personal control plane in cloud.upbound.io. Below are my test steps:
1. Verified baseline by successfully creating a claim using the now deleted examples/network.yaml.
```
$ kubectl get CompositeResourceDefinition
NAME                                              ESTABLISHED   OFFERED   AGE
compositeclusters.gcp.platformref.crossplane.io   True          True      31m
compositenetworks.gcp.platformref.crossplane.io   True          True      31m
gke.gcp.platformref.crossplane.io                 True                    31m
services.gcp.platformref.crossplane.io            True                    31m
```
```
$ kubectl get claim
NAME                                                             READY   CONNECTION-SECRET   AGE
network.gcp.platformref.crossplane.io/platform-ref-gcp-network   True                        1m
```
2. Deleted the claim and uninstalled the package. 
3. Reinstalled the unmodified package but pushed it as ldalorion/my-crossplane:platform-ref-gcp-0. 
```
$ kubectl get CompositeResourceDefinition
NAME                                              ESTABLISHED   OFFERED   AGE
compositeclusters.gcp.platformref.crossplane.io   True          True      31m
compositenetworks.gcp.platformref.crossplane.io   True          True      31m
gke.gcp.platformref.crossplane.io                 True                    31m
services.gcp.platformref.crossplane.io            True                    31m
```
4. Created the claim
```
$ kubectl get claim
NAME                                                             READY   CONNECTION-SECRET   AGE
network.gcp.platformref.crossplane.io/platform-ref-gcp-network   True                        1m
```
5. Deleted the claim and uninstalled the package. 
6. Removed ```spec.claimNames``` from network/definition.yaml
7. Installed the modified package ldalorion/my-crossplane:platform-ref-gcp-1.
```
$ kubectl get CompositeResourceDefinition 
NAME                                              ESTABLISHED   OFFERED   AGE
compositeclusters.gcp.platformref.crossplane.io   True          True      37s
compositenetworks.gcp.platformref.crossplane.io   True                    37s
gke.gcp.platformref.crossplane.io                 True                    37s
services.gcp.platformref.crossplane.io            True                    37s
```
8. Attempted to create a claim but could not.
```
$ kubectl apply -f examples/network.yaml
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "gcp.platformref.crossplane.io/v1alpha1, Resource=networks", GroupVersionKind: "gcp.platformref.crossplane.io/v1alpha1, Kind=Network"
Name: "platform-ref-gcp-network", Namespace: "default"
from server for: "examples/network.yaml": networks.gcp.platformref.crossplane.io "platform-ref-gcp-network" is forbidden: User "upbound-cloud-impersonator" cannot get resource "networks" in API group "gcp.platformref.crossplane.io" in the namespace "default"
```

I also conducted an upgrade test and the results were similar. However, the ```compositenetworks.gcp.platformref.crossplane.io``` still had and ```OFFERED``` status as ```True``` but I could not create a claim due to the removal ```spec.claimNames```. Steps to recreate the issue are similar to what's listed above but skip step 5 and instead of reinstalling the configuration as described in step 7, upgrade the configuration to the next version:

1. Install ldalorion/my-crossplane:platform-ref-gcp-0. 
```
$ kubectl get CompositeResourceDefinition
NAME                                              ESTABLISHED   OFFERED   AGE
compositeclusters.gcp.platformref.crossplane.io   True          True      31m
compositenetworks.gcp.platformref.crossplane.io   True          True      31m
gke.gcp.platformref.crossplane.io                 True                    31m
services.gcp.platformref.crossplane.io            True                    31m
```
2. Create claim
```
$ kubectl get claim
NAME                                                             READY   CONNECTION-SECRET   AGE
network.gcp.platformref.crossplane.io/platform-ref-gcp-network   True                        1m
```
4. Remove ```spec.claimNames``` from network/definition.yaml
5. Build and push the changes as ldalorion/my-crossplane:platform-ref-gcp-1. 
6. Update package to ldalorion/my-crossplane:platform-ref-gcp-1.
```
kubectl crossplane update configuration ldalorion-my-crossplane platform-ref-gcp-1
```
```
$ kubectl get CompositeResourceDefinition 
NAME                                              ESTABLISHED   OFFERED   AGE
compositeclusters.gcp.platformref.crossplane.io   True          True      31m
compositenetworks.gcp.platformref.crossplane.io   True          True      31m
gke.gcp.platformref.crossplane.io                 True                    31m
services.gcp.platformref.crossplane.io            True                    31m
``` 
8. Attempted to create a claim but could not despite XRD being marked as offered. 
```
$ kubectl apply -f examples/network.yaml
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "gcp.platformref.crossplane.io/v1alpha1, Resource=networks", GroupVersionKind: "gcp.platformref.crossplane.io/v1alpha1, Kind=Network"
Name: "platform-ref-gcp-network", Namespace: "default"
from server for: "examples/network.yaml": networks.gcp.platformref.crossplane.io "platform-ref-gcp-network" is forbidden: User "upbound-cloud-impersonator" cannot get resource "networks" in API group "gcp.platformref.crossplane.io" in the namespace "default"
```

I later deleted the claim and wait after a while to see if the status would change. However, it did not.

### CODE REVIEW

**Comment by Piotr1215** [comment]
:wave: @ldalorion , I really like your detailed tests and steps to reproduce the whole process :+1:

**Review by AaronME — COMMENTED** [review]
@ldalorion Nice work! Really great to see the detailed description of upgrade behavior.

I believe the XRD being offered is expected behavior. Removing claims removes the ability to create claims (XRCs), but users with cluster-level admin permission can still create Composite Resources (XRs) without a claim. So the CompositeResourceDefinition (XRD) _is_ still offered, just not as a claim.

Do you think this needs some notes in the README instructing users to manually cleanup the networks.gcp.platformref.crossplane.io CRD after upgrade?

**Comment by ldalorion** [comment]
@AaronME If I do a fresh install of the package without ```spec.claimNames``` defined, then is not listed as offered but I am still able to create a CompositeNetwork resource. So there's a discrepancy between install vs upgrade. I would expect both to have the same ```OFFERED``` status. Either an upgrade needs no longer be listed as ```OFFERED``` or the fresh install should still be listed as ```OFFERED```. And it is my understanding, as per [the original issue](https://github.com/upbound/platform-ref-aws/issues/25), the expectation is for it to be the former.   

I did more digging and I noticed that the ```gcp.platformref.crossplane.io/v1alpha1 Networks``` is not listed in the api-resources list when I do a fresh install of the package that doesn't have a Network claim. So as others have suspected the ```gcp.platformref.crossplane.io/v1alpha1 Networks``` CRD still exists in the cluster after the upgrade to the package with ```spec.claimNames``` removed from the XRD.

**Comment by ldalorion** [comment]
Looks like the only way to redact a claim is if the Composite was deleted. So if we want users to no longer offer a claim, we'd have to update the Reconciler. 
https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/offered/reconciler.go#L269

**Review by AaronME — APPROVED** [review]
This looks good to me! Thanks, @ldalorion!

**Pull request merged**
