### PR TITLE
Bump kube-prometheus-stack chart to latest

### PR DESCRIPTION
**Pull request by turkenh**
### Description of your changes

Pushes kube-prometheus-stack chart to the latest version. 
Also testing new e2e workflow.

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

With e2e workflow.

### CODE REVIEW

**Review by ytsarev — APPROVED** [review]

**Comment by ytsarev** [comment]
@hasheddan looks like you need to sign updated CLA

**Comment by jbw976** [comment]
Hmm, the CLA is acting a bit weird - I just clicked it and signed it and that turned it green.  I don't think @turkenh signed it also yet 🤔

**Comment by jbw976** [comment]
Hmm, actually @turkenh signed it Oct 17, 2022 12:10:04 PM, so that was possibly after the CLA bot first posted at https://github.com/upbound/platform-ref-gcp/pull/38#issuecomment-1281198161.  

So maybe me clicking the link and signing it just gave it the "kick" to look and see that @turkenh did in fact sign it a few days ago?

**Comment by turkenh** [comment]
> Hmm, actually @turkenh signed it Oct 17, 2022 12:10:04 PM, so that was possibly after the CLA bot first posted at [#38 (comment)](https://github.com/upbound/platform-ref-gcp/pull/38#issuecomment-1281198161).

Yes, I signed already and things are looking good on my end.

**Pull request merged**
